language: node_js
node_js:
- '0.12'
before_install: npm install -g grunt-cli
script:
  - '([ "${SAUCE_USERNAME}" ] && [ "${SAUCE_ACCESS_KEY}" ] && grunt test:ci) || ([ -z "${SAUCE_USERNAME}" ] || -z [ "${SAUCE_ACCESS_KEY}" ] && grunt test)'
